### ISSUE TITLE
what's the difference between  allRequirements and  singleRequirements

### ISSUE THREAD

**Issue by Ander456** [lovetoys/lovetoys#75]

**Comment by Nukesor** [comment]
Dude,
That part of the Library is not supposed to be used for writing games.
Anyway, we wrote a whole lot of examples and a API documentation in our Readme on how to use this Library.
If there is anything unclear on how to use the Lovetoys feel free to ask, but PLEASE read the API docs first and state your exact problem as well as the reason you don't understand something afterwards, instead of just asking a plain question without context.

If there is a valid question, we will update and clarify the docs.
